/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep.impl;

import edu.ulibertadores.PyDslRep.AbstractCrossMove;
import edu.ulibertadores.PyDslRep.DataMove;
import edu.ulibertadores.PyDslRep.PyDslRepPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Cross Move</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.ulibertadores.PyDslRep.impl.AbstractCrossMoveImpl#getTypeM <em>Type M</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AbstractCrossMoveImpl extends AbstractDataMoveImpl implements AbstractCrossMove
{
  /**
   * The cached value of the '{@link #getTypeM() <em>Type M</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeM()
   * @generated
   * @ordered
   */
  protected DataMove typeM;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractCrossMoveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PyDslRepPackage.Literals.ABSTRACT_CROSS_MOVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataMove getTypeM()
  {
    if (typeM != null && typeM.eIsProxy())
    {
      InternalEObject oldTypeM = (InternalEObject)typeM;
      typeM = (DataMove)eResolveProxy(oldTypeM);
      if (typeM != oldTypeM)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PyDslRepPackage.ABSTRACT_CROSS_MOVE__TYPE_M, oldTypeM, typeM));
      }
    }
    return typeM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataMove basicGetTypeM()
  {
    return typeM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeM(DataMove newTypeM)
  {
    DataMove oldTypeM = typeM;
    typeM = newTypeM;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PyDslRepPackage.ABSTRACT_CROSS_MOVE__TYPE_M, oldTypeM, typeM));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PyDslRepPackage.ABSTRACT_CROSS_MOVE__TYPE_M:
        if (resolve) return getTypeM();
        return basicGetTypeM();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PyDslRepPackage.ABSTRACT_CROSS_MOVE__TYPE_M:
        setTypeM((DataMove)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PyDslRepPackage.ABSTRACT_CROSS_MOVE__TYPE_M:
        setTypeM((DataMove)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PyDslRepPackage.ABSTRACT_CROSS_MOVE__TYPE_M:
        return typeM != null;
    }
    return super.eIsSet(featureID);
  }

} //AbstractCrossMoveImpl
