/*
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPyDslRepValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.ulibertadores.PyDslRep.PyDslRepPackage.eINSTANCE);
		return result;
	}
}
