/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ulibertadores.PyDslRep.AbstractMove#getTypeM <em>Type M</em>}</li>
 * </ul>
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getAbstractMove()
 * @model
 * @generated
 */
public interface AbstractMove extends AbstractDataMove
{
  /**
   * Returns the value of the '<em><b>Type M</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type M</em>' containment reference.
   * @see #setTypeM(DataMove)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getAbstractMove_TypeM()
   * @model containment="true"
   * @generated
   */
  DataMove getTypeM();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.AbstractMove#getTypeM <em>Type M</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type M</em>' containment reference.
   * @see #getTypeM()
   * @generated
   */
  void setTypeM(DataMove value);

} // AbstractMove
