/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ulibertadores.PyDslRep.Environment#getName <em>Name</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.Environment#getIp <em>Ip</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.Environment#getRobots <em>Robots</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.Environment#getMoves <em>Moves</em>}</li>
 * </ul>
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getEnvironment()
 * @model
 * @generated
 */
public interface Environment extends Entity
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getEnvironment_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.Environment#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ip</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip</em>' reference.
   * @see #setIp(IP)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getEnvironment_Ip()
   * @model
   * @generated
   */
  IP getIp();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.Environment#getIp <em>Ip</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip</em>' reference.
   * @see #getIp()
   * @generated
   */
  void setIp(IP value);

  /**
   * Returns the value of the '<em><b>Robots</b></em>' reference list.
   * The list contents are of type {@link edu.ulibertadores.PyDslRep.Robot}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots</em>' reference list.
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getEnvironment_Robots()
   * @model
   * @generated
   */
  EList<Robot> getRobots();

  /**
   * Returns the value of the '<em><b>Moves</b></em>' reference list.
   * The list contents are of type {@link edu.ulibertadores.PyDslRep.MoveCollection}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Moves</em>' reference list.
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getEnvironment_Moves()
   * @model
   * @generated
   */
  EList<MoveCollection> getMoves();

} // Environment
