/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turn</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getTurn()
 * @model
 * @generated
 */
public interface Turn extends DataMove
{
} // Turn
