/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep.impl;

import edu.ulibertadores.PyDslRep.AbstractDataMove;
import edu.ulibertadores.PyDslRep.PyDslRepPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Data Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractDataMoveImpl extends MinimalEObjectImpl.Container implements AbstractDataMove
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractDataMoveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PyDslRepPackage.Literals.ABSTRACT_DATA_MOVE;
  }

} //AbstractDataMoveImpl
