/**
 * generated by Xtext 2.13.0
 */
package edu.ulibertadores;

import edu.ulibertadores.PyDslRepStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PyDslRepStandaloneSetup extends PyDslRepStandaloneSetupGenerated {
  public static void doSetup() {
    new PyDslRepStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
