/*
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PyDslRepAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/ulibertadores/parser/antlr/internal/InternalPyDslRep.tokens");
	}
}
