/*
 * generated by Xtext 2.13.0
 */
package edu.ulibertadores


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PyDslRepStandaloneSetup extends PyDslRepStandaloneSetupGenerated {

	def static void doSetup() {
		new PyDslRepStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
