/*
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.ui.tests;

import com.google.inject.Injector;
import edu.ulibertadores.PyDslRep.ui.internal.PyDslRepActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PyDslRepUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PyDslRepActivator.getInstance().getInjector("edu.ulibertadores.PyDslRep");
	}

}
