/**
 * generated by Xtext 2.13.0
 */
package edu.ulibertadores.ide;

import edu.ulibertadores.ide.AbstractPyDslRepIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PyDslRepIdeModule extends AbstractPyDslRepIdeModule {
}
