/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Data Move</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getAbstractDataMove()
 * @model
 * @generated
 */
public interface AbstractDataMove extends EObject
{
} // AbstractDataMove
