/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ulibertadores.PyDslRep.DataMove#isName <em>Name</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.DataMove#getType <em>Type</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.DataMove#getVelocity <em>Velocity</em>}</li>
 * </ul>
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getDataMove()
 * @model
 * @generated
 */
public interface DataMove extends Entity
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(boolean)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getDataMove_Name()
   * @model
   * @generated
   */
  boolean isName();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.DataMove#isName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #isName()
   * @generated
   */
  void setName(boolean value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getDataMove_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.DataMove#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Velocity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Velocity</em>' attribute.
   * @see #setVelocity(String)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getDataMove_Velocity()
   * @model
   * @generated
   */
  String getVelocity();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.DataMove#getVelocity <em>Velocity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Velocity</em>' attribute.
   * @see #getVelocity()
   * @generated
   */
  void setVelocity(String value);

} // DataMove
