/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ulibertadores.PyDslRep.Move#getDistance <em>Distance</em>}</li>
 * </ul>
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends DataMove
{
  /**
   * Returns the value of the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance</em>' attribute.
   * @see #setDistance(String)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getMove_Distance()
   * @model
   * @generated
   */
  String getDistance();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.Move#getDistance <em>Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance</em>' attribute.
   * @see #getDistance()
   * @generated
   */
  void setDistance(String value);

} // Move
