/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.ulibertadores.PyDslRep.PyDslRepFactory
 * @model kind="package"
 * @generated
 */
public interface PyDslRepPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "PyDslRep";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ulibertadores.edu/PyDslRep";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "PyDslRep";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PyDslRepPackage eINSTANCE = edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.ModelImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Environment</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENVIRONMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.EntityImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.EnvironmentImpl <em>Environment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.EnvironmentImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getEnvironment()
   * @generated
   */
  int ENVIRONMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__NAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ip</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__IP = ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Robots</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__ROBOTS = ENTITY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Moves</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT__MOVES = ENTITY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Environment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENVIRONMENT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.RobotImpl <em>Robot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.RobotImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getRobot()
   * @generated
   */
  int ROBOT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__NAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__PORT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Wheels</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__WHEELS = ENTITY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Robot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.IPImpl <em>IP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.IPImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getIP()
   * @generated
   */
  int IP = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP__NAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ip</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP__IP = ENTITY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>IP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.WheelImpl <em>Wheel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.WheelImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getWheel()
   * @generated
   */
  int WHEEL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEEL__NAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEEL__RADIUS = ENTITY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Wheel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHEEL_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.MoveCollectionImpl <em>Move Collection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.MoveCollectionImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getMoveCollection()
   * @generated
   */
  int MOVE_COLLECTION = 6;

  /**
   * The feature id for the '<em><b>Concurrent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_COLLECTION__CONCURRENT = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_COLLECTION__NAME = ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Robot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_COLLECTION__ROBOT = ENTITY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Moves</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_COLLECTION__MOVES = ENTITY_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Move Collection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_COLLECTION_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.AbstractDataMoveImpl <em>Abstract Data Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.AbstractDataMoveImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getAbstractDataMove()
   * @generated
   */
  int ABSTRACT_DATA_MOVE = 7;

  /**
   * The number of structural features of the '<em>Abstract Data Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_DATA_MOVE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.AbstractMoveImpl <em>Abstract Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.AbstractMoveImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getAbstractMove()
   * @generated
   */
  int ABSTRACT_MOVE = 8;

  /**
   * The feature id for the '<em><b>Type M</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_MOVE__TYPE_M = ABSTRACT_DATA_MOVE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Abstract Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_MOVE_FEATURE_COUNT = ABSTRACT_DATA_MOVE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.AbstractCrossMoveImpl <em>Abstract Cross Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.AbstractCrossMoveImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getAbstractCrossMove()
   * @generated
   */
  int ABSTRACT_CROSS_MOVE = 9;

  /**
   * The feature id for the '<em><b>Type M</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CROSS_MOVE__TYPE_M = ABSTRACT_DATA_MOVE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Abstract Cross Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_CROSS_MOVE_FEATURE_COUNT = ABSTRACT_DATA_MOVE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.DataMoveImpl <em>Data Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.DataMoveImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getDataMove()
   * @generated
   */
  int DATA_MOVE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MOVE__NAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MOVE__TYPE = ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Velocity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MOVE__VELOCITY = ENTITY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Data Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_MOVE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.MoveImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getMove()
   * @generated
   */
  int MOVE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__NAME = DATA_MOVE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__TYPE = DATA_MOVE__TYPE;

  /**
   * The feature id for the '<em><b>Velocity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__VELOCITY = DATA_MOVE__VELOCITY;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__DISTANCE = DATA_MOVE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = DATA_MOVE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.TurnImpl <em>Turn</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.TurnImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getTurn()
   * @generated
   */
  int TURN = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN__NAME = DATA_MOVE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN__TYPE = DATA_MOVE__TYPE;

  /**
   * The feature id for the '<em><b>Velocity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN__VELOCITY = DATA_MOVE__VELOCITY;

  /**
   * The number of structural features of the '<em>Turn</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_FEATURE_COUNT = DATA_MOVE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.SensorImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__TYPE = ENTITY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ulibertadores.PyDslRep.impl.TypeSensorImpl <em>Type Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ulibertadores.PyDslRep.impl.TypeSensorImpl
   * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getTypeSensor()
   * @generated
   */
  int TYPE_SENSOR = 14;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_SENSOR__TYPE_NAME = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_SENSOR_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see edu.ulibertadores.PyDslRep.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ulibertadores.PyDslRep.Model#getEnvironment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Environment</em>'.
   * @see edu.ulibertadores.PyDslRep.Model#getEnvironment()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Environment();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see edu.ulibertadores.PyDslRep.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Environment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Environment</em>'.
   * @see edu.ulibertadores.PyDslRep.Environment
   * @generated
   */
  EClass getEnvironment();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.Environment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ulibertadores.PyDslRep.Environment#getName()
   * @see #getEnvironment()
   * @generated
   */
  EAttribute getEnvironment_Name();

  /**
   * Returns the meta object for the reference '{@link edu.ulibertadores.PyDslRep.Environment#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ip</em>'.
   * @see edu.ulibertadores.PyDslRep.Environment#getIp()
   * @see #getEnvironment()
   * @generated
   */
  EReference getEnvironment_Ip();

  /**
   * Returns the meta object for the reference list '{@link edu.ulibertadores.PyDslRep.Environment#getRobots <em>Robots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Robots</em>'.
   * @see edu.ulibertadores.PyDslRep.Environment#getRobots()
   * @see #getEnvironment()
   * @generated
   */
  EReference getEnvironment_Robots();

  /**
   * Returns the meta object for the reference list '{@link edu.ulibertadores.PyDslRep.Environment#getMoves <em>Moves</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Moves</em>'.
   * @see edu.ulibertadores.PyDslRep.Environment#getMoves()
   * @see #getEnvironment()
   * @generated
   */
  EReference getEnvironment_Moves();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Robot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Robot</em>'.
   * @see edu.ulibertadores.PyDslRep.Robot
   * @generated
   */
  EClass getRobot();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.Robot#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ulibertadores.PyDslRep.Robot#getName()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.Robot#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see edu.ulibertadores.PyDslRep.Robot#getPort()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Port();

  /**
   * Returns the meta object for the reference list '{@link edu.ulibertadores.PyDslRep.Robot#getWheels <em>Wheels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Wheels</em>'.
   * @see edu.ulibertadores.PyDslRep.Robot#getWheels()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_Wheels();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.IP <em>IP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>IP</em>'.
   * @see edu.ulibertadores.PyDslRep.IP
   * @generated
   */
  EClass getIP();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.IP#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ulibertadores.PyDslRep.IP#getName()
   * @see #getIP()
   * @generated
   */
  EAttribute getIP_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.IP#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip</em>'.
   * @see edu.ulibertadores.PyDslRep.IP#getIp()
   * @see #getIP()
   * @generated
   */
  EAttribute getIP_Ip();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Wheel <em>Wheel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wheel</em>'.
   * @see edu.ulibertadores.PyDslRep.Wheel
   * @generated
   */
  EClass getWheel();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.Wheel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ulibertadores.PyDslRep.Wheel#getName()
   * @see #getWheel()
   * @generated
   */
  EAttribute getWheel_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.Wheel#getRadius <em>Radius</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Radius</em>'.
   * @see edu.ulibertadores.PyDslRep.Wheel#getRadius()
   * @see #getWheel()
   * @generated
   */
  EAttribute getWheel_Radius();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.MoveCollection <em>Move Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Collection</em>'.
   * @see edu.ulibertadores.PyDslRep.MoveCollection
   * @generated
   */
  EClass getMoveCollection();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.MoveCollection#isConcurrent <em>Concurrent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Concurrent</em>'.
   * @see edu.ulibertadores.PyDslRep.MoveCollection#isConcurrent()
   * @see #getMoveCollection()
   * @generated
   */
  EAttribute getMoveCollection_Concurrent();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.MoveCollection#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ulibertadores.PyDslRep.MoveCollection#getName()
   * @see #getMoveCollection()
   * @generated
   */
  EAttribute getMoveCollection_Name();

  /**
   * Returns the meta object for the reference '{@link edu.ulibertadores.PyDslRep.MoveCollection#getRobot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Robot</em>'.
   * @see edu.ulibertadores.PyDslRep.MoveCollection#getRobot()
   * @see #getMoveCollection()
   * @generated
   */
  EReference getMoveCollection_Robot();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ulibertadores.PyDslRep.MoveCollection#getMoves <em>Moves</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Moves</em>'.
   * @see edu.ulibertadores.PyDslRep.MoveCollection#getMoves()
   * @see #getMoveCollection()
   * @generated
   */
  EReference getMoveCollection_Moves();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.AbstractDataMove <em>Abstract Data Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Data Move</em>'.
   * @see edu.ulibertadores.PyDslRep.AbstractDataMove
   * @generated
   */
  EClass getAbstractDataMove();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.AbstractMove <em>Abstract Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Move</em>'.
   * @see edu.ulibertadores.PyDslRep.AbstractMove
   * @generated
   */
  EClass getAbstractMove();

  /**
   * Returns the meta object for the containment reference '{@link edu.ulibertadores.PyDslRep.AbstractMove#getTypeM <em>Type M</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type M</em>'.
   * @see edu.ulibertadores.PyDslRep.AbstractMove#getTypeM()
   * @see #getAbstractMove()
   * @generated
   */
  EReference getAbstractMove_TypeM();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.AbstractCrossMove <em>Abstract Cross Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Cross Move</em>'.
   * @see edu.ulibertadores.PyDslRep.AbstractCrossMove
   * @generated
   */
  EClass getAbstractCrossMove();

  /**
   * Returns the meta object for the reference '{@link edu.ulibertadores.PyDslRep.AbstractCrossMove#getTypeM <em>Type M</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type M</em>'.
   * @see edu.ulibertadores.PyDslRep.AbstractCrossMove#getTypeM()
   * @see #getAbstractCrossMove()
   * @generated
   */
  EReference getAbstractCrossMove_TypeM();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.DataMove <em>Data Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Move</em>'.
   * @see edu.ulibertadores.PyDslRep.DataMove
   * @generated
   */
  EClass getDataMove();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.DataMove#isName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ulibertadores.PyDslRep.DataMove#isName()
   * @see #getDataMove()
   * @generated
   */
  EAttribute getDataMove_Name();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.DataMove#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see edu.ulibertadores.PyDslRep.DataMove#getType()
   * @see #getDataMove()
   * @generated
   */
  EAttribute getDataMove_Type();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.DataMove#getVelocity <em>Velocity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Velocity</em>'.
   * @see edu.ulibertadores.PyDslRep.DataMove#getVelocity()
   * @see #getDataMove()
   * @generated
   */
  EAttribute getDataMove_Velocity();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see edu.ulibertadores.PyDslRep.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.Move#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see edu.ulibertadores.PyDslRep.Move#getDistance()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Distance();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Turn <em>Turn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn</em>'.
   * @see edu.ulibertadores.PyDslRep.Turn
   * @generated
   */
  EClass getTurn();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see edu.ulibertadores.PyDslRep.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.Sensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ulibertadores.PyDslRep.Sensor#getName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Name();

  /**
   * Returns the meta object for the containment reference '{@link edu.ulibertadores.PyDslRep.Sensor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see edu.ulibertadores.PyDslRep.Sensor#getType()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Type();

  /**
   * Returns the meta object for class '{@link edu.ulibertadores.PyDslRep.TypeSensor <em>Type Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Sensor</em>'.
   * @see edu.ulibertadores.PyDslRep.TypeSensor
   * @generated
   */
  EClass getTypeSensor();

  /**
   * Returns the meta object for the attribute '{@link edu.ulibertadores.PyDslRep.TypeSensor#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Name</em>'.
   * @see edu.ulibertadores.PyDslRep.TypeSensor#getTypeName()
   * @see #getTypeSensor()
   * @generated
   */
  EAttribute getTypeSensor_TypeName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PyDslRepFactory getPyDslRepFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.ModelImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Environment</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENVIRONMENT = eINSTANCE.getModel_Environment();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.EntityImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.EnvironmentImpl <em>Environment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.EnvironmentImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getEnvironment()
     * @generated
     */
    EClass ENVIRONMENT = eINSTANCE.getEnvironment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENVIRONMENT__NAME = eINSTANCE.getEnvironment_Name();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENVIRONMENT__IP = eINSTANCE.getEnvironment_Ip();

    /**
     * The meta object literal for the '<em><b>Robots</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENVIRONMENT__ROBOTS = eINSTANCE.getEnvironment_Robots();

    /**
     * The meta object literal for the '<em><b>Moves</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENVIRONMENT__MOVES = eINSTANCE.getEnvironment_Moves();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.RobotImpl <em>Robot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.RobotImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getRobot()
     * @generated
     */
    EClass ROBOT = eINSTANCE.getRobot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__NAME = eINSTANCE.getRobot_Name();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__PORT = eINSTANCE.getRobot_Port();

    /**
     * The meta object literal for the '<em><b>Wheels</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__WHEELS = eINSTANCE.getRobot_Wheels();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.IPImpl <em>IP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.IPImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getIP()
     * @generated
     */
    EClass IP = eINSTANCE.getIP();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IP__NAME = eINSTANCE.getIP_Name();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IP__IP = eINSTANCE.getIP_Ip();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.WheelImpl <em>Wheel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.WheelImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getWheel()
     * @generated
     */
    EClass WHEEL = eINSTANCE.getWheel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHEEL__NAME = eINSTANCE.getWheel_Name();

    /**
     * The meta object literal for the '<em><b>Radius</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHEEL__RADIUS = eINSTANCE.getWheel_Radius();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.MoveCollectionImpl <em>Move Collection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.MoveCollectionImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getMoveCollection()
     * @generated
     */
    EClass MOVE_COLLECTION = eINSTANCE.getMoveCollection();

    /**
     * The meta object literal for the '<em><b>Concurrent</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_COLLECTION__CONCURRENT = eINSTANCE.getMoveCollection_Concurrent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_COLLECTION__NAME = eINSTANCE.getMoveCollection_Name();

    /**
     * The meta object literal for the '<em><b>Robot</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE_COLLECTION__ROBOT = eINSTANCE.getMoveCollection_Robot();

    /**
     * The meta object literal for the '<em><b>Moves</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE_COLLECTION__MOVES = eINSTANCE.getMoveCollection_Moves();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.AbstractDataMoveImpl <em>Abstract Data Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.AbstractDataMoveImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getAbstractDataMove()
     * @generated
     */
    EClass ABSTRACT_DATA_MOVE = eINSTANCE.getAbstractDataMove();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.AbstractMoveImpl <em>Abstract Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.AbstractMoveImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getAbstractMove()
     * @generated
     */
    EClass ABSTRACT_MOVE = eINSTANCE.getAbstractMove();

    /**
     * The meta object literal for the '<em><b>Type M</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_MOVE__TYPE_M = eINSTANCE.getAbstractMove_TypeM();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.AbstractCrossMoveImpl <em>Abstract Cross Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.AbstractCrossMoveImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getAbstractCrossMove()
     * @generated
     */
    EClass ABSTRACT_CROSS_MOVE = eINSTANCE.getAbstractCrossMove();

    /**
     * The meta object literal for the '<em><b>Type M</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_CROSS_MOVE__TYPE_M = eINSTANCE.getAbstractCrossMove_TypeM();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.DataMoveImpl <em>Data Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.DataMoveImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getDataMove()
     * @generated
     */
    EClass DATA_MOVE = eINSTANCE.getDataMove();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_MOVE__NAME = eINSTANCE.getDataMove_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_MOVE__TYPE = eINSTANCE.getDataMove_Type();

    /**
     * The meta object literal for the '<em><b>Velocity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_MOVE__VELOCITY = eINSTANCE.getDataMove_Velocity();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.MoveImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__DISTANCE = eINSTANCE.getMove_Distance();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.TurnImpl <em>Turn</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.TurnImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getTurn()
     * @generated
     */
    EClass TURN = eINSTANCE.getTurn();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.SensorImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__TYPE = eINSTANCE.getSensor_Type();

    /**
     * The meta object literal for the '{@link edu.ulibertadores.PyDslRep.impl.TypeSensorImpl <em>Type Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ulibertadores.PyDslRep.impl.TypeSensorImpl
     * @see edu.ulibertadores.PyDslRep.impl.PyDslRepPackageImpl#getTypeSensor()
     * @generated
     */
    EClass TYPE_SENSOR = eINSTANCE.getTypeSensor();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_SENSOR__TYPE_NAME = eINSTANCE.getTypeSensor_TypeName();

  }

} //PyDslRepPackage
