/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ulibertadores.PyDslRep.Robot#getName <em>Name</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.Robot#getPort <em>Port</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.Robot#getWheels <em>Wheels</em>}</li>
 * </ul>
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getRobot()
 * @model
 * @generated
 */
public interface Robot extends Entity
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getRobot_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.Robot#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getRobot_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.Robot#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

  /**
   * Returns the value of the '<em><b>Wheels</b></em>' reference list.
   * The list contents are of type {@link edu.ulibertadores.PyDslRep.Wheel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wheels</em>' reference list.
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getRobot_Wheels()
   * @model
   * @generated
   */
  EList<Wheel> getWheels();

} // Robot
