/**
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.PyDslRep;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ulibertadores.PyDslRep.Sensor#getName <em>Name</em>}</li>
 *   <li>{@link edu.ulibertadores.PyDslRep.Sensor#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends Entity
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getSensor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.Sensor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(TypeSensor)
   * @see edu.ulibertadores.PyDslRep.PyDslRepPackage#getSensor_Type()
   * @model containment="true"
   * @generated
   */
  TypeSensor getType();

  /**
   * Sets the value of the '{@link edu.ulibertadores.PyDslRep.Sensor#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(TypeSensor value);

} // Sensor
