/*
 * generated by Xtext 2.18.0.M3
 */
package edu.ulibertadores.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPyDslRepScopeProvider extends DelegatingScopeProvider {
}
