/**
 * generated by Xtext 2.13.0
 */
package edu.ulibertadores.ui;

import edu.ulibertadores.ui.AbstractPyDslRepUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PyDslRepUiModule extends AbstractPyDslRepUiModule {
  public PyDslRepUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
