/**
 * generated by Xtext 2.13.0
 */
package edu.ulibertadores.validation;

import edu.ulibertadores.validation.AbstractPyDslRepValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PyDslRepValidator extends AbstractPyDslRepValidator {
}
